Conference capstone
akos29/conference pull request #4
Opened 2022-10-20 01:29 UTC by akos29

### Hello Microverse

In this pull request I included the following:

- Create a mobile part of the home and about webpages 
- Add the desktop version and the interaction part of the webpages 
- Add JavaScript for the menu and generate HTML on the fly.
- Update the styling

2022-10-20 01:34 UTC, Bondok6 reviewed
## Hi @akos29 🙋‍♂️, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that doesn't have Linters, kindly add `.github/workflows` folders and `linters.yml` file to setup Linters correctly
> For this project, you should use [html-css-js](https://github.com/microverseinc/linters-config/tree/master/html-css-js) Linters.
1. Linter should be set up correctly for this repository.
1. Linter result should be green, this means that the last commit have a green check mark (✅)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-20 11:32 UTC, christianbiring1 requested changes
Hi @akos29 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request :heavy_multiplication_x: 
![Invalid](https://user-images.githubusercontent.com/97100091/196935987-77cd403a-d198-499a-8878-06a214b45f4d.gif)

You have submitted a project, that: 
- [x] Is not documented in a professional way. `Kindly make sure you give appropriate credit to the author in your README as said in the project requirements`
- [ ] `Kindly make sure you have deployed your application on GitHub pages with the correct branch(conference-capstone)`
- [ ] `Kindly make sure you include the link to your loom video presenting your project in your README or here in the PR summary`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-21 07:31 UTC, franclobo requested changes
Hi @akos29, 

# Required changes ♻️ 

Good job so far!
You are doing it well 👍🏽 there are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [x] I couldn't find where you defined the colors like `--bs-primary` or `--bs-secondary`, please 🙏🏽  use the colors of the original design in your CSS file.

![image](https://user-images.githubusercontent.com/58642949/197138104-33bfb2e7-dd28-442b-a63f-8be579d791eb.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-21 07:31 UTC, franclobo commented on assets/js/main.js
> +    pp: './assets/images/speaker 2.jpg',
- [x] Please 🙏🏽 correct the path of the images to be able to see the images in the deployment 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/197130882-740d5727-6b24-482f-83fd-a0ff770072dd.png)

2022-10-21 07:31 UTC, franclobo commented on assets/css/about.css
>  }
- [x] There are differences between the original design and yours in the size of this section, kindly correct the size to be similar to the original design 👇🏽 

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/197131669-c149a7b6-b943-4ca2-92bf-3756cba4fb8a.png) | ![image](https://user-images.githubusercontent.com/58642949/197131816-3788436e-a30d-4fea-a64a-d3bbf592bfa9.png) |

2022-10-21 07:31 UTC, franclobo commented on about.html
> +			</footer>
- [ ] There are small differences in the footer of the mobile version, please 🙏🏽 correct this section on the home page and the about page to be similar to the original version.

![image](https://user-images.githubusercontent.com/58642949/197134263-28044c0c-a474-4cc3-abfd-52263928eac4.png)

2022-10-21 07:31 UTC, franclobo commented on about.html
> +					<div class="detail">
- [ ] Please correct the size of this section on the about page to be similar to the original version 👇🏽 

| Original version | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/197134803-ab237323-5e53-4d03-a9a6-63128eb7fab9.png) | ![image](https://user-images.githubusercontent.com/58642949/197134917-07f25f17-a01a-4316-a0e7-681178424aa9.png) |

2022-10-21 07:31 UTC, franclobo commented on about.html
> +								<a class="nav-link btn">ADF Campaign</a>
- [ ] There are two navbars in the original design, please 🙏🏽 add the black navbar.

![image](https://user-images.githubusercontent.com/58642949/197135275-4213603c-e6de-41d7-912e-afe00a67140f.png)

2022-10-21 07:31 UTC, franclobo commented on index.html
>  								<a class="nav-link btn">ADF Campaign</a>
- [ ] There are two navbars in the original design, please 🙏🏽 add the black navbar 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/197135584-1536ddf1-2e92-4678-97c3-800e2e76cc32.png)

2022-10-21 07:31 UTC, franclobo commented on README.md
> +- Please refer to my brief [demonstration](https://www.loom.com/share/fe99979688214cc8b3bd83a11b8214f9) about the website. Thank you in advance for watching.
- [ ] Kindly highlight some interesting piece of code or something you built that you are very proud of.

2022-10-21 07:31 UTC, franclobo commented on about.html
> +						</button>
- [ ] I couldn't see the hamburger button in the mobile version, please 🙏🏽 fix it.

![image](https://user-images.githubusercontent.com/58642949/197136639-60d35efe-0416-4107-9631-a3fb32c2b483.png)

2022-10-21 23:23 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @akos29 , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 23:30 UTC, merged